# Generated by Django 4.2.7 on 2024-01-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='doj',
            field=models.DateField(default='2024-01-16'),
        ),
    ]
