# Generated by Django 4.2.7 on 2024-01-17 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRMSApp', '0002_employeedetail_doj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='doj',
            field=models.DateField(),
        ),
    ]
